spring.application.name=profitly-api

spring.datasource.url=jdbc:postgresql://localhost:5432/profitly
spring.datasource.username=${POSTGRE_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.docker.compose.enabled=false

brapi.base-url=https://brapi.dev
brapi.token=${BRAPI_TOKEN}

profitly.scheduler.stock-sync-hourly-cron=0 0 * * * *

spring.web.cors.enabled=false

api.security.token.secret=${JWT_SECRET:profitly-dev-secret-change-in-production}
google.client-id=
